### ISSUE TITLE
Generating / Getting Heightmaps

### ISSUE THREAD

**Issue by Nipeno** [Endebert/squadmc-maps#15]
I recently figured that some of the Squad Maps provided by the tool are outdated,
so I tried taking matters into my own hand and fixing it, without much success.

Would be amazing if you would be able to tell me how you get the heightmaps etc.
so I can make a fork of this project with all updated maps + heightmaps.

**Comment by sh4rkman** [comment]
@Nipeno I'm digging into the sdk right now, what map did you find wrong?

**Comment by Nipeno** [comment]
> @Nipeno I'm digging into the sdk right now, what map did you find wrong?

I mean the new map was missing last time I checked and the shooting range also wasn't updated if I remember correctly.
