### ISSUE TITLE
Map updates

### ISSUE THREAD

**Issue by Hawkins627** [Endebert/squadmc-maps#8]
Will these maps be updating at all? At v14 we have a new official map as well as a few changes to older maps.

**Comment by Endebert** [comment]
Do you by chance know exactly which maps have been updated? I'll definitely know of the new map, for the rest I guess have to compare to v13.

**Comment by Hawkins627** [comment]
These are the observations I have made comparing SquadMC maps to v14 in-game maps:

Al Basrah - Minor changes and enhanced locations
Belaya - Pretty significant changes to terrain colors
Chora - Medium changes that enhance locations and terrain
Fools Road - Pretty significant changes to terrain colors
Gorodok - Pretty significant color changes to terrain
Kamdesh - No changes!
Kohat - Pretty significant changes adding buildings and smoothing terrain
Kokan - No changes!
Logar - Buildings and walls are way more pronounced and crisp
Mestia - Map cleaned up pretty significantly and more crisp
Narva - No changes!
Sumari - Minor changes with some buildings more pronounced
Yehorivka - Minor changes with some buildings more pronounced
Tallil - Minor changes with buildings and walls more pronounced

**Comment by Endebert** [comment]
Hey, so unfortunately there won't be any map updates until they release the v14 sdk, as the current game files are encrypted. I lack the skill & time to reverse-engineer the code to find the encryption key, so all we can do is wait.

I also tried to workaround this by taking high res screenshots, but unfortunately they don't capture the hud anymore.

Of course, if anyone can play this game in at least 4k and make screenshots of the changed maps with disabled grid & icons (new map needs a second screenshot with grid enabled, so I can calculate the map size), please provide them and I will make them available for the time being.

**Comment by Endebert** [comment]
Ok, so far I've added Skorpo (+ heightmap) to the game. Here's the list again so I can keep track of it:

- [ ] Al Basrah - Minor changes and enhanced locations
- [ ] Belaya - Pretty significant changes to terrain colors
- [ ] Chora - Medium changes that enhance locations and terrain
- [ ] Fools Road - Pretty significant changes to terrain colors
- [ ] Gorodok - Pretty significant color changes to terrain
- [ ] Kamdesh - No changes!
- [ ] Kohat - Pretty significant changes adding buildings and smoothing terrain
- [ ] Kokan - No changes!
- [ ] Logar - Buildings and walls are way more pronounced and crisp
- [ ] Mestia - Map cleaned up pretty significantly and more crisp
- [ ] Narva - No changes!
- [ ] Sumari - Minor changes with some buildings more pronounced
- [ ] Yehorivka - Minor changes with some buildings more pronounced
- [ ] Tallil - Minor changes with buildings and walls more pronounced

**Comment by Hawkins627** [comment]
Absolutely beautiful! Thank you so much for this update!
